repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args:
          - "--py38-plus"

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
      - id: blackdoc

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.2"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-ruff
        args: ["--fix"]
      - id: nbqa-isort
        args: ["--profile=black"]
        additional_dependencies: [isort==5.6.4]
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ["--py37-plus"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args:
          [
            "--extra-keys",
            "metadata.celltoolbar metadata.kernelspec",
            "metadata.language_info.codemirror_mode.version",
            "metadata.language_info.pygments_lexer",
            "metadata.language_info.version",
            "metadata.toc",
            "metadata.notify_time",
            "metadata.varInspector",
            "cell.metadata.heading_collapsed",
            "cell.metadata.hidden",
            "cell.metadata.code_folding",
            "cell.metadata.tags",
            "cell.metadata.init_cell",
          ]
