project:
  type: website
  render:
    - "pages/*.qmd"
    - "examples/*.ipynb"
    - "!examples/*.py"

website:
  page-navigation: true
  title: "Warp resampling"
  site-url: "https://developmentseed.org/warp-resample-profiling"
  repo-url: https://github.com/developmentseed/warp-resample-profiling
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: pages/index.qmd
        text: Welcome
      - section: Dataset preparation
        contents:
          - href: examples/earthdata-download.ipynb
            text: Download dataset for example
      - section: GDAL Python API
        contents:
          - href: examples/resample-gdal-netcdf-vsis3.ipynb
            text: NetCDF Driver + vsis3
      - section: GDAL Python API
        contents:
          - href: examples/resample-rioxarray-netcdf-vsis3.ipynb
            text: NetCDF Driver + vsis3

format:
  html:
    theme:
      light: [cosmo]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    toc-depth: 3
filters:
  - quarto
