project:
  type: website
  render:
    - "pages/*.qmd"
    - "examples/*.ipynb"
    - "!examples/*.py"

website:
  page-navigation: true
  title: "Geospatial reprojection in Python (2024)"
  repo-url: https://github.com/developmentseed/warp-resample-profiling
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    title: "Warp resampling"
    tools:
      - icon: github
        href: https://github.com/developmentseed/warp-resample-profiling
        text: "Warp resampling"
    contents:
      - href: pages/index.qmd
        text: Welcome
      - section: Dataset preparation
        contents:
          - href: examples/earthdata-download.ipynb
            text: Download and virtualize dataset
      - section: Resampling libraries
        contents:
          - section: GDAL Python API
            contents:
              - href: examples/resample-gdal-netcdf-vsis3.ipynb
                text: NetCDF Driver + vsis3 (remote)
              - href: examples/resample-gdal-vrt-local.ipynb
                text: NetCDF Driver + vrt (local)
              - href: examples/resample-gdal-netcdf-local.ipynb
                text: NetCDF Driver (local)
          - section: Rasterio
            contents:
              - href: examples/resample-rasterio-netcdf-vsis3.ipynb
                text: NetCDF Driver + vsis3
          - section: Rioxarray
            contents:
              - href: examples/resample-rioxarray-netcdf-vsis3.ipynb
                text: NetCDF Driver + vsis3
          - section: Open Data Cube
            contents:
              - href: examples/resample-odc-h5netcdf-.ipynb
                text: NetCDF Driver + vsis3
          - section: Pyresample
            contents:
              - href: examples/resample-pyresample-h5netcdf-.ipynb
                text: h5netcdf Driver
      - section: WIP Resampling methods
        contents:
          - section: XESMF
            contents:
              - href: examples/future-resample-xesmf-h5netcdf-.ipynb
                text: (Pending) h5netcdf Driver
          - section: ODC
            contents:
              - href: examples/future-resample-odc-zarr-kerchunk.ipynb
                text: (Pending) Zarr via kerchunk
          - section: PyGMT
            contents:
              - href: examples/future-resample-pygmt-netcdf-local.ipynb
                text: (Pending) NetCDF Driver
          - section: XCube
            contents:
              - href: examples/future-resample-xcube-h5netcdf-.ipynb
                text: (Pending) h5netcdf Driver
      - section: Profiling results
        contents:
          - href: examples/process-results.ipynb
            text: Memory and time usage

format:
  html:
    theme:
      light: [cosmo]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    toc-depth: 3
filters:
  - quarto
