project:
  type: website
  render:
    - "*.qmd"
    - "examples/*.ipynb"
    - "!examples/*.py"

website:
  page-navigation: true
  title: "Geospatial reprojection in Python (2024)"
  repo-url: https://github.com/developmentseed/warp-resample-profiling
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    title: "Warp resampling"
    tools:
      - icon: github
        href: https://github.com/developmentseed/warp-resample-profiling
        text: "Warp resampling"
    contents:
      - href: index.qmd
        text: Welcome
      - href: pages/slides.qmd
        text: Overview Slides
      - section: Dataset preparation
        contents:
          - href: examples/earthdata-download.ipynb
            text: Download and virtualize dataset
      - section: Resampling libraries
        contents:
          - section: Rasterio
            contents:
              - href: examples/rasterio/resample-rasterio-netcdf-local.ipynb
                text: NetCDF Driver (Local storage)
              - href: examples/rasterio/resample-rasterio-netcdf-vsis3.ipynb
                text: NetCDF Driver (S3 storage)
          - section: Rioxarray
            contents:
              - href: examples/rioxarray/resample-rioxarray-h5netcdf-local.ipynb
                text: H5NetCDF Driver (Local storage)
              - href: examples/rioxarray/resample-rioxarray-h5netcdf-.ipynb
                text: H5NetCDF Driver (S3 storage)
          - section: Open Data Cube
            contents:
              - href: examples/odc/resample-odc-h5netcdf-local.ipynb
                text: H5NetCDF Driver (Local storage)
              - href: examples/odc/resample-odc-h5netcdf-.ipynb
                text: H5NetCDF Driver (S3 storage)
          - section: Pyresample
            contents:
              - href: examples/pyresample/resample-pyresample-h5netcdf-local.ipynb
                text: H5NetCDF Driver (Local storage)
              - href: examples/pyresample/resample-pyresample-h5netcdf-.ipynb
                text: H5NetCDF Driver (S3 storage)
          - section: XESMF
            contents:
              - href: examples/xesmf/resample-xesmf-h5netcdf-local.ipynb
                text: H5NetCDF Driver (Local storage)
              - href: examples/xesmf/resample-xesmf-h5netcdf-.ipynb
                text: H5NetCDF Driver (S3 storage)
              - href: examples/xesmf/resample-xesmf-zarr-icechunk.ipynb
                text: Zarr Reader + Icechunk virtualization (S3 storage)
          - section: XESMF (with pre-generated weights)
            contents:
              - href: examples/xesmf/resample-xesmfcached-h5netcdf-local.ipynb
                text: H5NetCDF Driver (Local storage)
              - href: examples/xesmf/resample-xesmfcached-h5netcdf-.ipynb
                text: H5NetCDF Driver (S3 storage)
              - href: examples/xesmf/resample-xesmfcached-zarr-icechunk.ipynb
                text: Zarr Reader + Icechunk virtualization(S3 storage)
              - href: examples/xesmf/resample-xesmfcached-zarr-kerchunk.ipynb
                text: Zarr Reader + Kerchunk virtualization (S3 storage)

      - section: Profiling results
        contents:
          - href: examples/process-results.ipynb
            text: Memory and time usage (MURSST)
          - href: examples/process-gpm-results.ipynb
            text: Memory and time usage (GPM IMERG)

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    toc-depth: 3
filters:
  - quarto
