---
title: "Geospatial reprojection in Python (2024)"
subtitle: "WIP guidebook and profiling results for Python resampling methods"
---

## Welcome
This a work-in-progress guidebook on existing warp resampling / reprojection methods in Python, along with some memory and statistical wall-time profiling results.

### Environment Setup

The notebooks can be run on a JupyterHub environment using the docker image `quay.io/developmentseed/warp-resample-profiling:latest`, which is created using `repo2docker` using the Dockerfile contained within the `binder` directory.

### Caveat

This is a WIP guidebook. We are presenting early on in the development to guide discussions and future work. The output from different resampling methods has not yet been verified, important parameters (e.g., target no_data values) have not been set, and not all methods have been implemented. We encourage people to contribute by building on the notebooks in the `examples` directory or participating in discussions on this repo or on the Pangeo discourse.

### Acknowledgements

This work was made possible through support from [NASA IMPACT](https://impact.earthdata.nasa.gov/). Numerous people have guided development, especially Aimee Barciauskas ([@abarciauskas-bgse](https://github.com/abarciauskas-bgse)), Justus Magin ([@keewis](https://github.com/keewis)), and Michael Sumner ([@mdsumner](https://github.com/mdsumner)). The resources page contains references for source information. All mistakes my own.
