name: warp-resample-profiling
channels:
  - conda-forge
  - nodefaults
dependencies:
  - rioxarray
  - xarray
  - earthaccess
  - dask-core
  - distributed
  - flox
  - fsspec
  - h5netcdf
  - h5py
  - hdf5
  - netcdf4
  - numpy=2.1.1
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pytest-timeout
  - rasterio
  - scipy
  - zarr
  - xesmf
  - geoutils
  - pyresample
  - memray
  - jupyter
  - virtualizarr
  - pip:
      - morecantile
      - pyinstrument
