name: warp-resample-profiling
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask-core
  - distributed
  - flox
  - numpy
  - xarray
  # IO / auth libraries
  - boto3
  - earthaccess
  - fiona
  - fsspec
  - h5netcdf
  - h5py
  - hdf5
  - kerchunk
  - netcdf4
  - zarr
  - libgdal # core C++ library and all plugins
  # xesmf dependencies
  - shapely
  - cf_xarray
  - numba
  # esmf build dependencies
  - wget
  - curl
  - openmpi
  - perl
  - cmake
  - gnuconfig
  - gcc
  - gxx
  - gfortran
  - make
  - pkg-config
  # Resampling libraries
  - geoutils
  - pyresample
  - rasterio
  - rioxarray
  - scipy
  - odc-geo
  - xcube
  - pygmt
  # For profiling
  - pyinstrument
  - memray
  # For development
  - gcc
  - jupyter
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pytest-timeout
  # For development on the Hub
  - git
  - code-server
  - jupyter-vscode-proxy
  # For visualizing results
  - hvplot
  # For building the quarto book
  - jupytext
  - pip:
      - morecantile
      # For development on the Hub
      - gh-scoped-creds
      # Development versions for icechunk
      - git+https://github.com/pydata/sparse@main # latest stable release doesn't ensure NumPy 2.0 compatibility
