name: warp-resample-profiling
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask-core
  - distributed
  - flox
  - numpy
  - xarray
  - sparse
  # Preparing virtual datasets
  # - virtualizarr # Only use during preparation because dependency for numpy>=2.0.0 conflicts with sparse, xemsf
  # IO / auth libraries
  - boto3
  - earthaccess
  - fiona
  - fsspec
  - h5netcdf
  - h5py
  - hdf5
  - netcdf4
  - zarr
  - libgdal # core C++ library and all plugins
  # Resampling libraries
  - geoutils
  - pyresample
  - rasterio
  - rioxarray
  - scipy
  - xesmf>=0.8.0
  - odc-geo
  - xcube
  # For profiling
  - pyinstrument
  - memray
  # For development
  - jupyter
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pytest-timeout
  # For development on the Hub
  - git
  - code-server
  - jupyter-vscode-proxy
  # For visualizing results
  - hvplot
  # For building the quarto book
  - jupytext
  - pip:
      - morecantile
      # For development on the Hub
      - gh-scoped-creds
