name: warp-resample-profiling
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask-core
  - distributed
  - flox
  - numpy=2.1.1
  - xarray
  # IO libraries
  - earthaccess
  - fsspec
  - h5netcdf
  - h5py
  - hdf5
  - netcdf4
  - zarr
  - libgdal # core C++ library and all plugins
  # Resampling libraries
  - geoutils
  - pyresample
  - rasterio
  - rioxarray
  - scipy
  - virtualizarr
  - xesmf
  # For profiling
  - pyinstrument
  - memray
  # For development
  - jupyter
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pytest-timeout
  # For development on the Hub
  - git
  - code-server
  - jupyter-vscode-proxy
  # For visualizing results
  - hvplot
  # For building the quarto book
  - jupytext
  - pip:
      - morecantile
      # For development on the Hub
      - gh-scoped-creds
